FROM golang:1.24.1

WORKDIR /go/src/app
COPY . .

RUN go mod tidy
RUN go install github.com/cespare/reflex@latest

ENV PATH="/go/bin:${PATH}"

EXPOSE 8080

CMD ["reflex", "-r", "\\.go$", "-s", "--", "sh", "-c", "go run main.go"]
